// This file is maintained by running scripts/refresh-training.py script

= Red Hat OpenStack Administration I: Core Operations for Domain Operators (CL110)

[.big]#*Course description*#

*Learn to operate a Red Hat® OpenStack Platform private cloud and manage domain resources to secure and deploy modern, scalable cloud applications, networks and storage*

Red Hat OpenStack Administration I: Core Operations for Domain Operators (CL110) teaches you how to operate and manage a production Red Hat OpenStack Platform (RHOSP) single-site overcloud. You will learn how to create secure project environments in which to provision resources and manage security privileges that cloud users need to deploy scalable cloud applications. You will learn about OpenShift integration with load balancers, identity management, monitoring, proxies, and storage. You will also develop more troubleshooting and Day 2 operations skills in this course.

This course is based on Red Hat OpenStack Platform 16.1.

Following course completion, you will receive a 45-day extended access to hands-on labs for any course that includes a virtual environment.

*Note:* This course is offered as a five day virtual class or self-paced. Durations may vary based on the delivery. For full course details, scheduling, and pricing, select your location then “get started” on the right hand menu.[.big]#*Course content summary*#

Students in the Red Hat OpenStack Administration I: Core Operations for Domain Operators (CL110) course will focus on performing both routine and specialized tasks that are necessary to manage a production OpenStack overcloud domain. Students will manage OpenStack using both web-based and command-line interfaces.  Essential skills covered in the course include the following:

* Launch instances to satisfy various use case examples.
* Manage domains, projects, users, roles, and quota in a multitenant environment.
* Manage networks, subnets, routers, and floating IP addresses.
* Manage instance security with group rules and access keys.
* Create and manage block, object and shared storage within OpenStack.
* Perform instance launch customization with cloud-init.
* Deploy scalable applications using stack templates.

[.big]#*Audience for this course*#

This course is designed for cloud users who deploy application instances and stacks, domain operators who manage resources and security for cloud users, and any other cloud personnel interested in, or responsible for, maintaining applications on private or hybrid OpenStack clouds.  Any cloud persona, or personnel with roles that include performing technology evaluation, should attend this course to learn RHOSP operation and application deployment methods.

[.big]#*Prerequisites for this course*#

* Become a https://www.redhat.com/en/services/certification/rhcsa-991[Red Hat Certified System Administrator (RHCSA)] or demonstrate equivalent experience
* If you are not a RHCSA, you can https://skills.ole.redhat.com/[take a skill assessment] to gauge your level of knowledge.

For full details, or to enroll:
https://www.redhat.com/en/services/training/cl110-red-hat-openstack-administration-i
