// This file is maintained by running scripts/refresh-training.py script

= Introduction to Event-Driven Ansible (DO274)

*Create, deploy, and configure Event-Driven Ansible to run automation code when triggered by events sent by your IT infrastructure.*

[.big]#*Course Description*#

* Introduction to Event-Driven Ansible (DO274) is designed for system administrators, DevOps engineers, and other technical professionals who want to learn how to create, deploy, and configure Event-Driven Ansible (EDA) to run automation code triggered by events sent by supported event sources such as monitoring systems, webhooks, and Apache Kafka. Write Ansible Rulebooks and use them in Event-Driven Ansible controller to react upon events and remediate or resolve infrastructure issues. Learn about key use cases as examples of how to use Event-Driven Ansible  in your IT infrastructure.
* This course is based on Red Hat® Ansible Automation Platform 2.4.

[.big]#*Course Content Summary*#

* Explain what Event-Driven Ansible is, why it is important, and describe its architecture and some of its key use cases and benefits
* Read, write, and test basic Ansible Rulebooks that react to events from various sources
* Explain installation options for Event-Driven Ansible controller and how to install it
* Set up new projects, the automation decision environment, and integration with automation controller so that Event-Driven Ansible controller can launch job templates based on events monitored by Ansible Rulebooks
* Configure and use Event-Driven Ansible to react to events generated by Git operations, such as push notifications or pull requests, and be able to use this to build a GitOps workflow
* Configure Ansible to use network telemetry to automatically respond to events and implement remediation or configuration changes

[.big]#*Target Audience*#

* This course is designed for system administrators, DevOps engineers, network administrators, and other technical professionals who are responsible for ensuring rapid response to infrastructure or application events and are interested in implementing issue remediation and resolution with automation.

[.big]#*Recommended training*#

* https://skills.ole.redhat.com/[Take our free assessment] to gauge whether this offering is the best fit for your skills
* User-level experience with Red Hat Enterprise Linux and running commands from the shell required; RHCSA or RHCE-level skill recommended
* This course requires students to have basic knowledge of command-line Ansible, Visual Studio Code, and Git.  Experience with Red Hat Ansible Automation Platform 2 and automation controller is recommended

[.big]#*Technology considerations*#

* For virtual or self-paced learners:
** Internet access is required to run the exercises and labs
** BYOD/BYDW is not supported
* For classroom learners:
** Internet access is not required
** BYOD/BYDW is not supported

For full details, or to enroll:
https://www.redhat.com/en/services/training/introduction-event-driven-ansible-do274
