// This file is maintained by running scripts/refresh-training.py script

= Red Hat System Administration II (RH134)

[.big]#*Course Description*#

*Build the skills to perform the key tasks needed to become a full-time Linux administrator*

Red Hat System Administration II (RH134) is the second part of the RHCSA training track for IT professionals who have already attended https://www.redhat.com/en/services/training/rh124-red-hat-system-administration-i[Red Hat System Administration I]. The course goes deeper into core Linux system administration skills in storage configuration and management, installation and deployment of Red Hat Enterprise Linux, management of security features such as SELinux, control of recurring system tasks, management of the boot process and troubleshooting, basic system tuning, and command-line automation and productivity.  This course assumes that students have attended https://www.redhat.com/en/services/training/rh124-red-hat-system-administration-i[Red Hat System Administration I (RH124)].

Experienced Linux administrators who seek rapid preparation for the RHCSA certification should instead start with https://www.redhat.com/en/services/training/rh199-red-hat-certified-system-administrator-rapid-track-course[RHCSA Rapid Track (RH199)].

This course is based on Red Hat Enterprise Linux 9.0.

Following course completion, you will receive a 45-day extended access to hands-on labs for any course that includes a virtual environment.

*Note:* This course is offered as a five day in person class, a five day virtual class or is self-paced. Durations may vary based on the delivery. For full course details, scheduling, and pricing, select your location then “get started” on the right hand menu.

[.big]#*Course summary*#

* Install Red Hat Enterprise Linux using scalable methods
* Access security files, file systems, and networks
* Execute shell scripting and automation techniques
* Manage storage devices, logical volumes, and file systems
* Manage security and system access
* Control the boot process and system services
* Run containers

[.big]#*Audience for this course*#

This course is geared toward Windows system administrators, network administrators, and other system administrators who are interested in supplementing current skills or backstopping other team members, in addition to Linux system administrators who are responsible for these tasks:

* Configuring, installing, upgrading, and maintaining Linux systems using established standards and procedures
* Providing operational support
* Managing systems for monitoring system performance and availability
* Writing and deploying scripts for task automation and system administration

[.big]#*Recommended training*#

* Successful completion of https://www.redhat.com/en/services/training/rh124-red-hat-system-administration-i[Red Hat System Administration I (RH124)] is recommended.
*  Experienced Linux administrators seeking to accelerate their path toward becoming a Red Hat Certified System Administrator should start with the https://www.redhat.com/en/services/training/rh199-red-hat-certified-system-administrator-rapid-track-course[RHCSA Rapid Track course (RH199).]
* https://skills.ole.redhat.com/[Take our free assessment] to gauge whether this offering is the best fit for your skills.

[.big]#*Technology considerations*#

* There are no special technology requirements.
* This course is not designed for bring your own device (BYOD).
* Internet access is not required, but is recommended to allow students to research and access Red Hat online resources.

For full details, or to enroll:
https://www.redhat.com/en/services/training/rh134-red-hat-system-administration-ii
