// This file is maintained by running scripts/refresh-training.py script

= Red Hat Enterprise Linux Diagnostics and Troubleshooting (RH342)

[.big]#*Course description*#

*Diagnose problems, gather information, and fix common issues with Red Hat Enterprise Linux*

The Red Hat Enterprise Linux Diagnostics and Troubleshooting course (RH342) provides system administrators with the tools and techniques they need to successfully diagnose, and fix, a variety of potential issues. Students will work through hands-on problems in various subsystems to diagnose and fix common issues.

Students will learn how to apply the scientific method to a structured form of troubleshooting. This approach is then used troubleshooting various types of problems, including boot issues, hardware issues, storage issues, RPM issues, network issues, third-party application issues, security issues, and kernel issues. At the end of the course students can complete various comprehensive review labs to test their skills.

This course is based on Red Hat Enterprise Linux 8.4.

Following course completion, you will receive a 45-day extended access to hands-on labs for any course that includes a virtual environment.

*Note:* This course is offered as a five day virtual class or self-paced. Durations may vary based on the delivery. For full course details, scheduling, and pricing, select your location then “get started” on the right hand menu.

[.big]#*Course content summary*#

* Use the scientific method to approach troubleshooting
* Troubleshoot boot issues
* Troubleshoot security issues
* Troubleshoot storage issues
* Troubleshoot network issues

[.big]#*Audience for this course*#

The Red Hat Enterprise Linux Diagnostics and Troubleshooting course is aimed at senior system administrators who wish to learn more about troubleshooting.

[.big]#*Prerequisites for this course*#

Red Hat recommends these prerequisites:

* Have earned a https://www.redhat.com/certification/rhcsa[Red Hat Certified System Administrator (RHCSA)] or have similar experience
* It is recommend that students have earned a https://www.redhat.com/certification/rhce[Red Hat Certified Engineer (RHCE)] or have similar experience

For full details, or to enroll:
https://www.redhat.com/en/services/training/rh342-red-hat-enterprise-linux-diagnostics-and-troubleshooting
