// This file is maintained by running scripts/refresh-training.py script

= Red Hat Training: Open Practices for your DevOps Journey (TL250)

[.big]#*Course description*#

*Discover open practices for incremental process changes to assist in your DevOps transformation journey.*

Open Practices for your DevOps Journey (TL250) prepares a student to facilitate and participate in discovery, planning, and delivery of projects where DevOps transformation is desired.  At the end of this course, you will establish a toolbox of select practices and rethink your approach to cross-functional team projects. Utilizing new skills will enable your organization to effectively discover team purpose, align on project options, and deliver value that achieves target outcomes.

Following course completion, you will receive a 45-day extended access to hands-on labs for any course that includes a virtual environment.

*Note:* This course is self paced. Durations may vary based on the delivery. For full course details, scheduling, and pricing, select your location then “get started” on the right hand menu.

[.big]#*Course content summary*#

* Discovery practices that support creating alignment on who and what is desired to be created.
* Delivery practices that support creating quick and effective means to deliver and reflect.
* Options-pivot practices that support prioritization and organizing work to be logically completed.
* Foundational team practices that support team collaboration and communication, and technical concepts.
* How work visualization and remote collaboration can be done to support DevOps delivery methods.

[.big]#*Target audience*#

* Project Managers, Agile Coaches, Scrum Masters: Individuals facilitating project planning and execution who wish to adjust their approach and incrementally move the organization toward DevOps.
* System Administrators, SRE, application developers: Technical project team members participating in discovery, planning, and execution phases will accelerate the completion of these practices with greater detail.
* Leadership, product owners, key stakeholders: Individuals with a vested interest in project success or who provide oversight, goals, and objectives for why the project is needed will have greater insight into the process and ensure their requirements are captured.

[.big]#*Recommended training*#

* There are no prerequisites for this course.

[.big]#*Technology considerations*#

* This course does not have accompanying labs but may require the use of an internet browser to access several collaboration tools such as Miro or Trello.

For full details, or to enroll:
https://www.redhat.com/en/services/training/tl250-red-hat-training-open-practices-your-devops-journey
