////
Purpose
-------
This section should contain a minimal list of Red Hat associates who directly
participated. A good rule of thumb is to restrict the list to associates who
applied billable hours to the project in conjunction with this engagement.  A
typical list should include the delivery consultant(s), the project manager,
and the architect (if present and/or billing).  Also include the TSM if the TSM
was actively involved (i.e. attending status calls, escalations etc...)
////
.Red Hat Participants
[cols="3,4,5",options=header]
|===
|Name
|Role
|E-mail address

// Name
| Sumit Garg
// Role
| Delivery Manager
// Email Address
| sugarg@redhat.com

// Name
| Reena Tyagi
// Role
| Project Manager
// Email Address
| rtyagi@redhat.com

// Name
| Rajveer Singh
// Role
| Principal Consultant
// Email Address
| rajsingh@redhat.com

// Name
| Ritesh Dave
// Role
| Architect
// Email Address
| ritdav@redhat.com

// Name
| Surendra Singh
// Role
| Architect
// Email Address
| suresing@redhat.com

|===
