////
Purpose
-------
In the "Base" directory, this section is a placeholder which is to be
overwritten by implementation details specific to the product or products being
delivered.

If "TODO" appears in your document after the init script has been run, then
your product directory is missing a corresponding "implementation.adoc" which
should be created to provide a basic implementation framework for that product.
////

== Configure Catalogue Source and Image Content Source Policy

[source, yaml]
----
cat << EOF | oc apply -f -
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-redhat-operator-index-1
  namespace: openshift-marketplace
spec:
  image: invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp16/redhat/redhat-operator-index:v4.16
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-redhat-operator-index-2
  namespace: openshift-marketplace
spec:
  image: invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp18/redhat/redhat-operator-index:v4.18
  sourceType: grpc
EOF

----


----
[ocpvbsc2@invipb07moh1bast1sm ~]$ cat << EOF | oc apply -f -
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-redhat-operator-index-1
  namespace: openshift-marketplace
spec:
  image: invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp16/redhat/redhat-operator-index:v4.16
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-redhat-operator-index-2
  namespace: openshift-marketplace
spec:
  image: invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp18/redhat/redhat-operator-index:v4.18
  sourceType: grpc
EOF
catalogsource.operators.coreos.com/cs-redhat-operator-index-1 created
catalogsource.operators.coreos.com/cs-redhat-operator-index-2 created

----

== Configure Image Content Source Policy

[source, yaml]
----

cat << EOF | oc apply -f -
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-redhat-operator-index-1
  namespace: openshift-marketplace
spec:
  image: invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp16/redhat/redhat-operator-index:v4.16
  sourceType: grpc
---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: generic-1
spec:
  repositoryDigestMirrors:
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp16/ubi8
    source: registry.access.redhat.com/ubi8
---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: operator-1
spec:
  repositoryDigestMirrors:
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp16/rhceph
    source: registry.redhat.io/rhceph
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp16/rhel9
    source: registry.redhat.io/rhel9
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp16/rhel8
    source: registry.redhat.io/rhel8
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp16/openshift-logging
    source: registry.redhat.io/openshift-logging
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp16/lvms4
    source: registry.redhat.io/lvms4
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp16/odf4
    source: registry.redhat.io/odf4
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp16/openshift4
    source: registry.redhat.io/openshift4
---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: release-1
spec:
  repositoryDigestMirrors:
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp16/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp16/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-redhat-operator-index-2
  namespace: openshift-marketplace
spec:
  image: invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp18/redhat/redhat-operator-index:v4.18
  sourceType: grpc
---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: generic-2
spec:
  repositoryDigestMirrors:
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp18/ubi8
    source: registry.access.redhat.com/ubi8
---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: operator-2
spec:
  repositoryDigestMirrors:
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp18/openshift4
    source: registry.redhat.io/openshift4
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp18/odf4
    source: registry.redhat.io/odf4
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp18/lvms4
    source: registry.redhat.io/lvms4
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp18/rhel9
    source: registry.redhat.io/rhel9
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp18/rhceph
    source: registry.redhat.io/rhceph
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp18/rhel8
    source: registry.redhat.io/rhel8
---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: release-2
spec:
  repositoryDigestMirrors:
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp18/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - invipb07moh1ocprmsm.pbstd.vil.local:8443/ocp18/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
EOF
----

----
EOF source: quay.io/openshift-release-dev/ocp-releaseopenshift/release-imagesr-index:v4.18
catalogsource.operators.coreos.com/cs-redhat-operator-index-1 unchanged
imagecontentsourcepolicy.operator.openshift.io/generic-1 created
imagecontentsourcepolicy.operator.openshift.io/operator-1 created
imagecontentsourcepolicy.operator.openshift.io/release-1 created
catalogsource.operators.coreos.com/cs-redhat-operator-index-2 unchanged
imagecontentsourcepolicy.operator.openshift.io/generic-2 created
imagecontentsourcepolicy.operator.openshift.io/operator-2 created
imagecontentsourcepolicy.operator.openshift.io/release-2 created

----

== Disable Default catalog source

[source, bash]
----
oc patch operatorhub cluster --type json -p '[{"op": "add", "path":"/spec/disableAllDefaultSources", "value": true }]'
----

----
[ocpvbsc2@invipb07moh1bast1sm ~]$ oc get operatorhub cluster -oyaml
apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  annotations:
    capability.openshift.io/name: marketplace
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2026-02-27T22:38:50Z"
  generation: 2
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: a004b3dc-8284-4aea-bba3-b8247b5d679d
  resourceVersion: "177233"
  uid: a533619b-74ea-4c93-b0c1-6498e97a7e3b
spec:
  disableAllDefaultSources: true
status:
  sources:
  - disabled: true
    name: redhat-marketplace
    status: Success
  - disabled: true
    name: redhat-operators
    status: Success
  - disabled: true
    name: certified-operators
    status: Success
  - disabled: true
    name: community-operators
    status: Success
----


