////
Purpose
-------
In the "Base" directory, this section is a placeholder which is to be
overwritten by implementation details specific to the product or products being
delivered.

If "TODO" appears in your document after the init script has been run, then
your product directory is missing a corresponding "implementation.adoc" which
should be created to provide a basic implementation framework for that product.
////

== Create nmsatte operator folder
 
[source, bash]
----
mkdir -p ~/ocp4.18/operator/nmstate
cd ~/ocp4.18/operator/nmstate
----

== Deploy NM State operator

[source, yaml]
----
cat <<EOF > ~/ocp4.18/operator/nmstate/1_namespace-operator.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: openshift-nmstate
    name: openshift-nmstate
  name: openshift-nmstate
spec:
  finalizers:
    - kubernetes
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: NMState.v1.nmstate.io
  name: openshift-nmstate
  namespace: openshift-nmstate
spec:
  targetNamespaces:
    - openshift-nmstate
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/kubernetes-nmstate-operator.openshift-nmstate: ""
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kubernetes-nmstate-operator
  source: cs-redhat-operator-index-2
  sourceNamespace: openshift-marketplace
EOF
----
*Apply the Configuration File*

[source, bash]
----
oc apply -f ~/ocp4.18/operator/nmstate/1_namespace-operator.yaml
----

----
[ocpvbsc2@invipb07moh1bast1sm nmstate]$ oc apply -f ~/ocp4.18/operator/nmstate/1_namespace-operator.yaml
namespace/openshift-nmstate created
operatorgroup.operators.coreos.com/openshift-nmstate created
subscription.operators.coreos.com/kubernetes-nmstate-operator created
[ocpvbsc2@invipb07moh1bast1sm nmstate]$ oc get installplan -A
NAMESPACE           NAME            CSV                                               APPROVAL    APPROVED
openshift-nmstate   install-p54d4   kubernetes-nmstate-operator.4.18.0-202512031242   Automatic   true
[ocpvbsc2@invipb07moh1bast1sm nmstate]$ oc get csv -n openshift-nmstate
NAME                                              DISPLAY                       VERSION               REPLACES   PHASE
kubernetes-nmstate-operator.4.18.0-202512031242   Kubernetes NMState Operator   4.18.0-202512031242              Succeeded
----

== Create NMState Instance

[source, yaml]
----
cat <<EOF >> ~/ocp4.18/operator/nmstate/3_instance.yaml
---
apiVersion: nmstate.io/v1
kind: NMState
metadata:
  name: nmstate
EOF
----

*Apply the Configuration*

[source, bash]
----
oc apply -f ~/ocp4.18/operator/nmstate/3_instance.yaml
----

----
[ocpvbsc2@invipb07moh1bast1sm nmstate]$ oc apply -f ~/ocp4.18/operator/nmstate/3_instance.yaml
nmstate.nmstate.io/nmstate created
[ocpvbsc2@invipb07moh1bast1sm nmstate]$ oc get pod -n openshift-nmstate
NAME                                      READY   STATUS    RESTARTS   AGE
nmstate-console-plugin-6ff7998486-cztgj   1/1     Running   0          34s
nmstate-handler-5j6pd                     1/1     Running   0          34s
nmstate-handler-7j6w7                     1/1     Running   0          34s
nmstate-handler-mg9fl                     1/1     Running   0          34s
nmstate-metrics-7f7f7578db-s52wx          2/2     Running   0          34s
nmstate-operator-57658fcb48-vkvmg         1/1     Running   0          2m30s
nmstate-webhook-f8fb84555-tzb2p           1/1     Running   0          34s
----

== Create interface bond1.810 for ODF Installation

*Create nmstate file*
[source, yaml]
----
cat <<EOF > ~/ocp4.18/operator/nmstate/odf-bond1-master-1.yaml
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: odf-master1-bond1
spec:
  nodeSelector:
    kubernetes.io/hostname: invipb07moh1bsc21sm
  desiredState:
    interfaces:
      - name: bond1.810
        type: vlan
        state: up
        mtu: 9000
        vlan:
          base-iface: bond1
          id: 810
        ipv4:
          enabled: true
          address:
          - ip: 172.18.15.141
            prefix-length: 24
          dhcp: false
        ipv6:
          enabled: true
          address:
          - ip: 2400:5200:a000::c:100:105
            prefix-length: 121
          dhcp: false
      - name: bond1
        type: bond
        state: up
        mtu: 9000
        ipv4:
          enabled: false
        ipv6:
          enabled: false
        link-aggregation:
          mode: 802.3ad
          options:
            miimon: 100
            lacp_rate: 'fast'
          port:
           - ens1f1
           - ens4f1
EOF

cat <<EOF > ~/ocp4.18/operator/nmstate/odf-bond1-master-2.yaml

apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: odf-master2-bond1
spec:
  nodeSelector:
    kubernetes.io/hostname: invipb07moh1bsc22sm
  desiredState:
    interfaces:
      - name: bond1.810
        type: vlan
        state: up
        mtu: 9000
        vlan:
          base-iface: bond1
          id: 810
        ipv4:
          enabled: true
          address:
          - ip: 172.18.15.142
            prefix-length: 24
          dhcp: false
        ipv6:
          enabled: true
          address:
          - ip: 2400:5200:a000::c:100:106
            prefix-length: 121
          dhcp: false
      - name: bond1
        type: bond
        state: up
        mtu: 9000
        ipv4:
          enabled: false
        ipv6:
          enabled: false
        link-aggregation:
          mode: 802.3ad
          options:
            miimon: 100
            lacp_rate: 'fast'
          port:
           - ens1f1
           - ens4f1
EOF

cat <<EOF > ~/ocp4.18/operator/nmstate/odf-bond1-master-3.yaml
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: odf-master3-bond1
spec:
  nodeSelector:
    kubernetes.io/hostname: invipb07moh1bsc23sm
  desiredState:
    interfaces:
      - name: bond1.810
        type: vlan
        state: up
        mtu: 9000
        vlan:
          base-iface: bond1
          id: 810
        ipv4:
          enabled: true
          address:
          - ip: 172.18.15.143
            prefix-length: 24
          dhcp: false
        ipv6:
          enabled: true
          address:
          - ip: 2400:5200:a000::c:100:107
            prefix-length: 121
          dhcp: false
      - name: bond1
        type: bond
        state: up
        mtu: 9000
        ipv4:
          enabled: false
        ipv6:
          enabled: false
        link-aggregation:
          mode: 802.3ad
          options:
            miimon: 100
            lacp_rate: 'fast'
          port:
           - ens1f1
           - ens4f1
EOF

----

*Create master-3 interface*
[source, bash]
----
oc apply -f ~/ocp4.18/operator/nmstate/odf-bond1-master-3.yaml
----

----
[ocpvbsc2@invipb07moh1bast1sm nmstate]$ oc apply -f ~/ocp4.18/operator/nmstate/odf-bond1-master-3.yaml
nodenetworkconfigurationpolicy.nmstate.io/nbi-msater3-bond0 created
[ocpvbsc2@invipb07moh1bast1sm nmstate]$ oc get nnce
NAME                                    STATUS      STATUS AGE   REASON
invipb07moh1bsc23sm.odf-master3-bond1   Available   2m22s        SuccessfullyConfigured
----

*Create master-1 and master-2 interface*
[source, bash]
----
oc apply -f ~/ocp4.18/operator/nmstate/odf-bond1-master-1.yaml
oc apply -f ~/ocp4.18/operator/nmstate/odf-bond1-master-2.yaml
----
----
[ocpvbsc2@invipb07moh1bast1sm nmstate]$ oc apply -f ~/ocp4.18/operator/nmstate/odf-bond1-master-1.yaml
oc apply -f ~/ocp4.18/operator/nmstate/odf-bond1-master-2.yaml
nodenetworkconfigurationpolicy.nmstate.io/odf-master1-bond1 created
nodenetworkconfigurationpolicy.nmstate.io/odf-master2-bond1 created
[ocpvbsc2@invipb07moh1bast1sm nmstate]$ oc get nncp
NAME                STATUS      REASON
odf-master1-bond1   Available   SuccessfullyConfigured
odf-master2-bond1   Available   SuccessfullyConfigured
odf-master3-bond1   Available   SuccessfullyConfigured
----

== Create NPI Interface on Bond0

*Create Configuration File*

[source, yaml]

----
cat <<EOF > ~/ocp4.18/operator/nmstate/nbi-bond1-master-1.yaml
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nbi-msater1-bond0
spec:
  nodeSelector:
    kubernetes.io/hostname: invipb07moh1bsc21sm
  desiredState:
    interfaces:
      - name: bond0.808
        type: vlan
        state: up
        vlan:
          base-iface: bond0
          id: 808
        ipv4:
          enabled: true
          address:
          - ip: 100.109.182.55
            prefix-length: 28
          dhcp: false
        ipv6:
          enabled: true
          address:
          - ip: 2400:5200:a000::c:100:f5
            prefix-length: 124
          dhcp: false
EOF

cat <<EOF > ~/ocp4.18/operator/nmstate/nbi-bond1-master-2.yaml
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nbi-msater2-bond0
spec:
  nodeSelector:
    kubernetes.io/hostname: invipb07moh1bsc22sm
  desiredState:
    interfaces:
      - name: bond0.808
        type: vlan
        state: up
        vlan:
          base-iface: bond0
          id: 808
        ipv4:
          enabled: true
          address:
          - ip: 100.109.182.56
            prefix-length: 28
          dhcp: false
        ipv6:
          enabled: true
          address:
          - ip: 2400:5200:a000::c:100:f6
            prefix-length: 124
          dhcp: false
EOF

cat <<EOF > ~/ocp4.18/operator/nmstate/nbi-bond1-master-3.yaml
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nbi-msater3-bond0
spec:
  nodeSelector:
    kubernetes.io/hostname: invipb07moh1bsc23sm
  desiredState:
    interfaces:
      - name: bond0.808
        type: vlan
        state: up
        vlan:
          base-iface: bond0
          id: 808
        ipv4:
          enabled: true
          address:
          - ip: 100.109.182.57
            prefix-length: 28
          dhcp: false
        ipv6:
          enabled: true
          address:
          - ip: 2400:5200:a000::c:100:f7
            prefix-length: 124
          dhcp: false
EOF
----

*Create nbi Interface on master-3*

[source, bash]
----
oc apply -f ~/ocp4.18/operator/nmstate/nbi-bond1-master-3.yaml
----

----
[invibh19ptn1bast1sm ~ ocpvbsc3]$oc apply -f ~/ocp4.18/operator/nmstate/nbi-bond1-master-3.yaml
nodenetworkconfigurationpolicy.nmstate.io/nbi-msater-3 created
[ocpvbsc2@invipb07moh1bast1sm nmstate]$ oc get nncp | grep nbi
nbi-msater3-bond0   Available   SuccessfullyConfigured
----


*Create nbi Interface on master-1 and master-2*

[source, bash]
----
oc apply -f ~/ocp4.18/operator/nmstate/nbi-bond1-master-1.yaml
oc apply -f ~/ocp4.18/operator/nmstate/nbi-bond1-master-2.yaml
----

----
[ocpvbsc2@invipb07moh1bast1sm ~]$oc apply -f ~/ocp4.18/operator/nmstate/nbi-bond1-master-1.yaml
oc apply -f ~/ocp4.18/operator/nmstate/nbi-bond1-master-2.yaml
nodenetworkconfigurationpolicy.nmstate.io/nbi-msater-1 created
nodenetworkconfigurationpolicy.nmstate.io/nbi-msater-2 created
[ocpvbsc2@invipb07moh1bast1sm ~]$ oc get nncp | grep nbi
nbi-msater1-bond0   Available   SuccessfullyConfigured
nbi-msater2-bond0   Available   SuccessfullyConfigured
nbi-msater3-bond0   Available   SuccessfullyConfigured
----