////
Purpose
-------
In the "Base" directory, this section is a placeholder which is to be
overwritten by implementation details specific to the product or products being
delivered.

If "TODO" appears in your document after the init script has been run, then
your product directory is missing a corresponding "implementation.adoc" which
should be created to provide a basic implementation framework for that product.
////

== Create loki configuration folder
 
[source, bash]
----
mkdir -p ~/ocp4.18/operator/etcd
cd ~/ocp4.18/operator/etcd
----

== ETCD Encription
*Edit the apiserver configuration*
[source, bash]
----
oc edit apiserver
----

----
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    oauth-apiserver.openshift.io/secure-token-storage: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-12-22T07:25:59Z"
  generation: 2
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 3d03dbfb-b6e5-4bab-935b-875841346495
  resourceVersion: "9320459"
  uid: 9cd5b968-7e74-477f-96df-b39ea5f1af11
spec:
  audit:
    profile: Default
  encryption:
    type: aescbc
----

*Validate the ETCD Encription*
[source, bash]
----
oc get openshiftapiserver -o=jsonpath='{range.items[0].status.conditions[?(@.type=="Encrypted")]}{.reason}{"\n"}{.message}{"\n"}'

oc get kubeapiserver -o=jsonpath='{range.items[0].status.conditions[?(@.type=="Encrypted")]}{.reason}{"\n"}{.message}{"\n"}'

oc get authentication.operator.openshift.io -o=jsonpath='{range.items[0].status.conditions[?(@.type=="Encrypted")]}{.reason}{"\n"}{.message}{"\n"}'
----

----
[ocpvbsc2@invipb07moh1bast1sm etcd-backup]$ oc get openshiftapiserver -o=jsonpath='{range .items[0].status.conditions[?(@.type=="Encrypted")]}{.reason}{"\n"}{.message}{"\n"}{end}'


[ocpvbsc2@invipb07moh1bast1sm etcd-backup]$ oc get apiserver -o yaml > apiserver.yaml
[ocpvbsc2@invipb07moh1bast1sm etcd-backup]$ ll
total 12
-rw-r--r--. 1 ocpvbsc2 ocpvbsc2 1248 Mar  3 13:09 1_cronjob_resource.yaml
-rw-r--r--. 1 ocpvbsc2 ocpvbsc2 2303 Mar  3 14:45 2_backup-cronjob.yaml
-rw-r--r--. 1 ocpvbsc2 ocpvbsc2  749 Mar  3 14:49 apiserver.yaml


[ocpvbsc2@invipb07moh1bast1sm etcd-backup]$ oc get apiserver -o yaml
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: APIServer
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      oauth-apiserver.openshift.io/secure-token-storage: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2026-02-27T22:38:50Z"
    generation: 1
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: a004b3dc-8284-4aea-bba3-b8247b5d679d
    resourceVersion: "926"
    uid: b29d2af7-923f-4cbe-8195-36abc35fcf02
  spec:
    audit:
      profile: Default
kind: List
metadata:
  resourceVersion: ""
[ocpvbsc2@invipb07moh1bast1sm etcd-backup]$ oc edit apiserver
apiserver.config.openshift.io/cluster edited
[ocpvbsc2@invipb07moh1bast1sm etcd-backup]$ oc get apiserver -o yaml
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: APIServer
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      oauth-apiserver.openshift.io/secure-token-storage: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2026-02-27T22:38:50Z"
    generation: 2
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: a004b3dc-8284-4aea-bba3-b8247b5d679d
    resourceVersion: "1988583"
    uid: b29d2af7-923f-4cbe-8195-36abc35fcf02
  spec:
    audit:
      profile: Default
    encryption:
      type: aescbc
kind: List
metadata:
  resourceVersion: ""
  
following value need to add :-

    encryption:
      type: aescbc

encription in progress 


[ocpvbsc2@invipb07moh1bast1sm etcd-backup]$ oc get openshiftapiserver -o=jsonpath='{range .items[0].status.conditions[?(@.type=="Encrypted")]}{.reason}{"\n"}{.message}{"\n"}{end}'
EncryptionInProgress


[ocpvbsc2@invipb07moh1bast1sm etcd-backup]$ oc get co
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication                             4.18.17   True        True          False      3d10h   APIServerDeploymentProgressing: deployment/apiserver.openshift-oauth-apiserver: 1/3 pods have been updated to the latest generation and 2/3 pods are available
baremetal                                  4.18.17   True        False         False      3d10h
cloud-controller-manager                   4.18.17   True        False         False      3d10h
cloud-credential                           4.18.17   True        False         False      3d10h
cluster-autoscaler                         4.18.17   True        False         False      3d10h
config-operator                            4.18.17   True        False         False      3d10h
console                                    4.18.17   True        False         False      3d10h
control-plane-machine-set                  4.18.17   True        False         False      3d10h
csi-snapshot-controller                    4.18.17   True        False         False      3d10h
dns                                        4.18.17   True        False         False      3d10h
etcd                                       4.18.17   True        False         False      3d10h
image-registry                             4.18.17   True        False         False      3d10h
ingress                                    4.18.17   True        False         False      3d10h
insights                                   4.18.17   True        False         False      3d10h
kube-apiserver                             4.18.17   True        False         False      3d10h
kube-controller-manager                    4.18.17   True        False         False      3d10h
kube-scheduler                             4.18.17   True        False         False      3d10h
kube-storage-version-migrator              4.18.17   True        False         False      161m
machine-api                                4.18.17   True        False         False      3d10h
machine-approver                           4.18.17   True        False         False      3d10h
machine-config                             4.18.17   True        False         False      3d10h
marketplace                                4.18.17   True        False         False      3d10h
monitoring                                 4.18.17   True        False         False      3d10h
network                                    4.18.17   True        False         False      3d10h
node-tuning                                4.18.17   True        False         False      3d10h
olm                                        4.18.17   True        False         False      161m
openshift-apiserver                        4.18.17   True        True          False      2d15h   APIServerDeploymentProgressing: deployment/apiserver.openshift-apiserver: 1/3 pods have been updated to the latest generation and 2/3 pods are available
openshift-controller-manager               4.18.17   True        False         False      3d10h
openshift-samples                          4.18.17   True        False         False      3d10h
operator-lifecycle-manager                 4.18.17   True        False         False      3d10h
operator-lifecycle-manager-catalog         4.18.17   True        False         False      3d10h
operator-lifecycle-manager-packageserver   4.18.17   True        False         False      25h
service-ca                                 4.18.17   True        False         False      3d10h
storage                                    4.18.17   True        False         False      3d10h


[ocpvbsc2@invipb07moh1bast1sm etcd-backup]$ oc get openshiftapiserver -o=jsonpath='{range .items[0].status.conditions[?(@.type=="Encrypted")]}{.reason}{"\n"}{.message}{"\n"}{end}'
EncryptionCompleted
All resources encrypted: routes.route.openshift.io
[ocpvbsc2@invipb07moh1bast1sm etcd-backup]$
[ocpvbsc2@invipb07moh1bast1sm etcd-backup]$ oc get openshiftapiserver -o=jsonpath='{range.items[0].status.conditions[?(@.type=="Encrypted")]}{.reason}{"\n"}{.message}{"\n"}'
oc get kubeapiserver -o=jsonpath='{range.items[0].status.conditions[?(@.type=="Encrypted")]}{.reason}{"\n"}{.message}{"\n"}'
oc get authentication.operator.openshift.io -o=jsonpath='{range.items[0].status.conditions[?(@.type=="Encrypted")]}{.reason}{"\n"}{.message}{"\n"}'
EncryptionCompleted
All resources encrypted: routes.route.openshift.io


EncryptionCompleted
All resources encrypted: secrets, configmaps


EncryptionCompleted
All resources encrypted: oauthaccesstokens.oauth.openshift.io, oauthauthorizetokens.oauth.openshift.io


[ocpvbsc2@invipb07moh1bast1sm etcd-backup]$

================================================================================

openshift ingress pod replica default is 3 and require 3 

[ocpvbsc2@invipb07moh1bast1sm ~]$ oc get pod -n openshift-ingress -o wide
NAME                              READY   STATUS    RESTARTS   AGE     IP               NODE                  NOMINATED NODE   READINESS GATES
router-default-5765f85d59-c6qjq   1/1     Running   0          3h19m   100.109.182.72   invipb07moh1bsc21sm   <none>           <none>
router-default-5765f85d59-dwsvs   1/1     Running   0          3h29m   100.109.182.74   invipb07moh1bsc23sm   <none>           <none>
[ocpvbsc2@invipb07moh1bast1sm ~]$ oc get pod -n openshift-ingress-operator -o wide
NAME                                READY   STATUS    RESTARTS   AGE     IP            NODE                  NOMINATED NODE   READINESS GATES
ingress-operator-7b9b484d4d-jq7cl   2/2     Running   0          3h20m   10.130.0.35   invipb07moh1bsc21sm   <none>           <none>
[ocpvbsc2@invipb07moh1bast1sm ~]$

[ocpvbsc2@invipb07moh1bast1sm ~]$ oc patch ingresscontroller/default -n openshift-ingress-operator --type=merge -p '{"spec":{"replicas": 3}}'
ingresscontroller.operator.openshift.io/default patched


[ocpvbsc2@invipb07moh1bast1sm ~]$ oc get pod -n openshift-ingress -o wide
NAME                              READY   STATUS    RESTARTS   AGE     IP               NODE                  NOMINATED NODE   READINESS GATES
router-default-5765f85d59-c6qjq   1/1     Running   0          3h21m   100.109.182.72   invipb07moh1bsc21sm   <none>           <none>
router-default-5765f85d59-dwsvs   1/1     Running   0          3h31m   100.109.182.74   invipb07moh1bsc23sm   <none>           <none>
router-default-5765f85d59-kcvsz   1/1     Running   0          9s      100.109.182.73   invipb07moh1bsc22sm   <none>           <none>
[ocpvbsc2@invipb07moh1bast1sm ~]$

----

== ETCD Backup
*Creae Cronjob Resource*
[source, yaml]
----
cat <<EOF >  ~/ocp4.18/operator/etcd/1_cronjob_resource.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: ocp-etcd-backup
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-backup-sa
  namespace: ocp-etcd-backup

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-etcd-backup
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/exec
  verbs:
  - get
  - list
  - create
  - delete
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - etcds
  verbs:
  - get
  - list
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcd-backup-rolebinding
subjects:
  - kind: ServiceAccount
    name: etcd-backup-sa
    namespace: ocp-etcd-backup
roleRef:
  kind: ClusterRole
  name: cluster-etcd-backup
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-privileged-scc
  namespace: ocp-etcd-backup
subjects:
  - kind: ServiceAccount
    name: etcd-backup-sa
    namespace: ocp-etcd-backup
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
  apiGroup: rbac.authorization.k8s.io

EOF
----

*Create ETCD Backup Cronjob*

[source, yaml]
----
cat <<EOF >  ~/ocp4.18/operator/etcd/2_backu-cronjob.yaml
---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: openshift-backup
  namespace: ocp-etcd-backup
  labels:
    app: openshift-backup
spec:
  schedule: "24 7 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: openshift-backup
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: openshift-backup
        spec:
          containers:
            - name: backup
              image: "quay.ocplab.surendra.redhat.com:8443/openshift/release@sha256:8ef769e53648ef07d1236ea7b9fb73a051134e8b38e1e2506a8b2fe6b0717cdd"
              command:
                - "/bin/bash"
                - "-c"
                - oc get no -l node-role.kubernetes.io/master --no-headers -o name | xargs -I {} --  oc debug {}  --to-namespace=ocp-etcd-backup -- bash -c 'chroot /host  sudo mount -t nfs 10.64.40.1:/srv/nfs/share /home/core/backup/ && chroot /host sudo -E /usr/local/bin/cluster-backup.sh /home/core/backup/ && chroot /host sudo -E find /home/core/backup/ -type f -mmin +"9" -delete'
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: "ClusterFirst"
          serviceAccountName: "etcd-backup-sa"
          serviceAccount: "etcd-backup-sa"
EOF
----